Play travis
Otus-DevOps-2021-11/kirdyashkindi_infra pull request #1
Opened 2021-12-14 21:04 UTC by kirdyashkindi

# Выполнено ДЗ №4

 - [ v] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
- добавлены необходимые для выполнения задания файлы
- сделан тестовый канал в чате
- чат интегрирован с github

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ v] Выставил label с номером домашнего задания
 - [ v] Выставил label с темой домашнего задания

2021-12-15 08:30 UTC, mrgreyves requested changes
Здравствуйте!
Задание выполнено не полностью, рекомендую свериться с методичкой
Вам нужно добавить проверки (Github Actions Workflow)

2021-12-15 08:30 UTC, mrgreyves commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
Сюда смотрим внимательно =)

2021-12-16 20:06 UTC, kirdyashkindi commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
Не подумал что надо будет поправить скрипт) Спасибо. Единственное что меня смущает, ошибка в auto-assign, хотя написано что все проверки пройдены - это норм? 

И ещё, мне нужно сделать новый ПР?

2021-12-17 08:04 UTC, mrgreyves commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 1)
Не вижу ошибки в auto-assign,
Если точнее, то он у вас не добавлен, но думаю это не критично

2021-12-17 08:05 UTC, mrgreyves approved these changes
Здравствуйте!)
Апрув!

2021-12-17 10:03 UTC, merged